apiVersion: v1
kind: ReplicationController
metadata:
  name: dynamodb
spec:
  replicas: 1
  selector:
    app: dynamodb
  template:
    metadata:
      name: dynamodb
      labels:
        app: dynamodb
    spec:
      containers:
      - name: dynomodb
        image: dwmkerr/dynamodb
        ports:
        - containerPort: 8000
