apiVersion: v1
kind: Service
metadata:
  labels:
    name: dynamodb-service
  name: dynamodb-service
spec:
  selector:
    app: dynamodb
  type: NodePort
  ports:
  - name: dynomodb
    port: 8000
    targetPort: 8000
    nodePort: 30036
    protocol: TCP
